### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by miRNA67** [leylabmpi/CoreGenomePrimers#1]
Hello,

I installed in my pc using snakemake and git, but when I try to run the test I get the following error:

it is possible to have a step by step of how to run the tutorial in snakemake?

Using temporary directory: tests/tmp/cabana/LLPRIMER_22943487/ 
Using output directory: tests/output_pecto/ 
Building DAG of jobs...
MissingInputException in rule clusters_blastx_nontarget_format in line 77 of /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/./bin/cgp/nontarget/cds/Snakefile:
Missing input files for rule clusters_blastx_nontarget_format:
    output: tests/output_pecto/cgp/nontarget/cds_blastx.tsv
    affected files:
        None

Thanks

**Comment by nick-youngblut** [comment]
You need to update the paths to the database files in the config: https://github.com/leylabmpi/CoreGenomePrimers/blob/master/config.yaml

I've updated the README to help with that. For more convenience, I'll upload all of the required files to our ftp server: http://ftp.tue.mpg.de/ebio/projects/

**Comment by nick-youngblut** [comment]
The databases have been uploaded to http://ftp.tue.mpg.de/ebio/projects/CoreGenomePrimers/ 

Feel free to re-open the issue if you experience any problems with the databases.

**Comment by miRNA67** [comment]
Thank you for the help!!!

Now the pipeline is running!!! Now I have the next error:

Activating conda environment: .snakemake/conda/4399104154e1404dd5821e6396e5680d_
[Thu Sep 22 15:00:18 2022]
Error in rule primers_design:
    jobid: 96
    output: tests/tmp/cabana/LLPRIMER_22943487/primers_raw/cds/10/primers_degen.fna, tests/tmp/cabana/LLPRIMER_22943487/primers_raw/cds/10/primers_expand.fna, tests/tmp/cabana/LLPRIMER_22943487/primers_raw/cds/10/primers.tsv
    log: tests/output_pecto/logs/cgp/primers/design/cds/10.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/5c4280d88a5bb1e9f08bb8027c1720fe_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "tests/tmp/cabana/LLPRIMER_22943487/primers_raw/cds/10/primers.tsv" | perl -pe 's/\.tsv$//'`
        bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 0 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX tests/tmp/cabana/LLPRIMER_22943487/clusters_core/cds/cluster_10.afa 2> tests/output_pecto/logs/cgp/primers/design/cds/10.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

And the 10.log is:

2022-09-22 15:00:15,985 - Designing primers...
2022-09-22 15:00:18,546 -   No. of raw degen primer sets: 1000
2022-09-22 15:00:18,546 - Calculating degenerate primers...
Traceback (most recent call last):
  File "bin/scripts/primer_design.py", line 756, in <module>
    main(args)
  File "bin/scripts/primer_design.py", line 733, in main
    internal_oligo=args.make_oligo)
  File "bin/scripts/primer_design.py", line 465, in calc_degen
    window=window_3prime)
  File "bin/scripts/primer_design.py", line 355, in expand_degen
    degen = reduce((lambda x, y: x * y), [len(x) for x in seq])
NameError: name 'reduce' is not defined

Please, I need your help!!

**Comment by nick-youngblut** [comment]
The error was due to a version issue with python. It should now be fixed. To be clear, if you run into a *new* problem, please open up a new issue. "some issues" isn't really a specific title for your problem(s).

Note: running the BLAST vs nt/nr will require a lot of memory (and time) by default. I hope that you have sufficient computational resources.

**Comment by miRNA67** [comment]
Thank you for your help!!!
