### ISSUE TITLE
clusters_blastx_format.py killed

### ISSUE THREAD

**Issue by miRNA67** [leylabmpi/CoreGenomePrimers#2]
Thank you for your help in the last issues!! Now, I am still running the test file and have a problem with the next command:

/home/CoreGenomePrimers/bin/scripts/clusters_blastx_format.py /home/CoreGenomePrimers/tests/tmp/cabana/LLPRIMER_22943487/blastn_nontarget/hits.txt /media/backup/DB/accession/nr_accession-geneNames.pkl /home/CoreGenomePrimers/tests/output_pecto/cgp/nontarget/rrna_blastn.tsv 2> /home/CoreGenomePrimers/tests/output_pecto/logs/cgp/annotate/blastn_nontarget_format/all.log 1>&2
Killed

Is a problem with the RAM memory? I am working with a PC with 64 gb of RAM. What is the minimum size of RAM memory to run this part of the pipeline? is possible to decrease the RAM requirement of this script?

Thank you!!!

**Comment by nick-youngblut** [comment]
Did you pull the updated code? I changed the old name `LLPRIMER` to `CoreGenomePrimers`, which suggests that you are still using the old code.

`Killed` can often mean that you are lacking sufficient compute resources. What system are you running the pipeline on? Please provide hardware and OS info. Thanks.

**Comment by miRNA67** [comment]
Now I pulled the updated code and running in a Ubuntu 20.04.2 LTS with 128 gb of RAM without problems (with 64 gb of RAM I have the issue).

Thank you!!!
