### ISSUE TITLE
Snakemake bug

### ISSUE THREAD

**Issue by miRNA67** [leylabmpi/CoreGenomePrimers#3]
I am running the pipeline without problems until I have the next issue about snakemake:

[Sun Sep 25 03:50:46 2022]
rule clusters_blastx_nontarget_format:
    input: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/blastx_nontarget/hits.txt, /media/backup/DB/accession/nr_accession-geneNames.pkl
    output: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/nontarget/cds_blastx.tsv
    log: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/logs/cgp/annotate/blastx_nontarget_format/all.log
    jobid: 21
    benchmark: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/benchmarks/cgp/annotate/blastx_nontarget_format/all.txt
    reason: Missing output files: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/nontarget/cds_blastx.tsv; Input files updated by another job: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/blastx_nontarget/hits.txt
    resources: tmpdir=/tmp, time=59, mem_gb_pt=50

[Sun Sep 25 03:59:09 2022]
Finished job 21.
72 of 151 steps (48%) done
Removing temporary output /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/blastx_nontarget/hits.txt.
BUG: Out of jobs ready to be started, but not all files built yet. Please check https://github.com/snakemake/snakemake/issues/823 for more information.
Remaining jobs:
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_6/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_6/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_6/primers.tsv
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/5/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/5/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/5/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_7/primers_degen.txt
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/6/blastn.txt
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/rrna/cluster_2/amplicons.bed
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/5/blastn.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/6/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/6/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/6/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/rrna/cluster_2/primers_degen.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/6/blastn.txt
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/rrna/cluster_1/amplicons.bed
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/7/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/7/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/7/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/rrna/cluster_1/primers_degen.txt
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/2/blastn.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/7/blastn.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_2/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_2/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_2/primers.tsv
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/1/blastn.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_1/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_1/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_1/primers.tsv
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/8/blastn.txt
 - seqkit_amplicon_merge: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/amplicons.tsv
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_8/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_8/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_8/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_6/amplicons.bed
 - all: 
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_6/primers_degen.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/2/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/2/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/2/primers.tsv
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/3/blastn.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_3/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_3/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_3/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_9/amplicons.bed
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/rrna/2/blastn.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/2/blastn.txt
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_9/primers_degen.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/1/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/1/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/1/primers.tsv
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_2/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_2/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_2/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_2/amplicons.bed
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/1/blastn.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/1/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/1/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/1/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_2/primers_degen.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/8/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/8/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/8/primers.tsv
 - clusters_nuc_rep_seqs: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps.fna
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_4/amplicons.bed
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/3/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/3/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/3/primers.tsv
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/8/blastn.txt
 - clusters_blastdb_create: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.ndb, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.nhr, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.nin, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.not, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.nsq, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.ntf, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters_core/combined_nuc_db.nto
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_4/primers_degen.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/3/blastn.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_1/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_1/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/rrna/cluster_1/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_1/amplicons.bed
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/9/blastn.txt
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/rrna/1/blastn.txt
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_1/primers_degen.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/9/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/9/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/9/primers.tsv
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/2/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/2/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/rrna/2/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_5/amplicons.bed
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/9/blastn.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/rrna/2/blastn.txt
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_5/primers_degen.txt
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/rrna/1/blastn.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_4/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_4/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_4/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_8/amplicons.bed
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/5/blastn.txt
 - clusters_mmseqs_reps: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps_db, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps_db.dbtype, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps_db.index, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps_db_h, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/clusters/cluster_reps.tsv
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/4/blastn.txt
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_8/primers_degen.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_5/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_5/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_5/primers.tsv
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_9/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_9/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_9/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_10/amplicons.bed
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/10/blastn.txt
 - clusters_concat_info: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/core_clusters_info.tsv
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_10/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_10/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_10/primers.tsv
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/4/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/4/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/4/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_10/primers_degen.txt
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_3/amplicons.bed
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/4/blastn.txt
 - primers_blastn_other_taxa: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_nontarget_blastn/cds/7/blastn.txt
 - primers_blastn_crosshyb_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/10/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/10/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_filtered/cds/10/primers.tsv
 - seqkit_amplicon_format: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_3/primers_degen.txt
 - primers_blastn_other_taxa_filter: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_7/primers_degen.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_7/primers_expand.fna, /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final/cds/cluster_7/primers.tsv
 - seqkit_amplicon: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/amplicon/cds/cluster_7/amplicons.bed
 - primers_blastn_crosshyb: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_2359642/primers_crosshyb_blastn/cds/10/blastn.txt
 - primers_concat_info: /home/Documents/coregenomeprimers/last/CoreGenomePrimers/tests/output_pecto/cgp/primers_final_info.tsv

Pipeline failed! Creating report... 

What is the best option to solve this bug? Because the link https://github.com/snakemake/snakemake/issues/823 is confused. I am using snakemake 7.14.0

**Comment by nick-youngblut** [comment]
https://github.com/snakemake/snakemake/issues/823 doesn't provide a good solution. You could try re-running from the start, instead of resuming an old, failed run. It could also be associated with high file latency, but it sounds like you are not using a networked file system.

**Comment by miRNA67** [comment]
Yes, I re-runed a new analysis and got the same error either using the commands: 

snakemake --cores all --use-conda

Or

snakemake --cores all --use-conda --keep-going

Do you recommend other command to test your pipeline?

Thanks in advanced

**Comment by nick-youngblut** [comment]
Thanks for checking. It appears that the BLAST job didn't return any hits, which resulted in a lack of an output file, so the snakemake pipeline run failed. I've added `touch` commands to the BLAST jobs, so at the very least, you will have empty output files, if there are no BLAST hits

**Comment by miRNA67** [comment]
Thank you! Now is running!!!
